version: '3'

services:

  postgres:
    container_name: postgres_containerimserso
    image: postgres:latest
    restart: always    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: E&uoj)~'8z-'!r}&
      POSTGRES_DB: DBImserso
    ports:
      - "5432:5432"
    volumes:     
      - ./sql/imserso_arranged_v1.sql:/docker-entrypoint-initdb.d/imserso_arranged_v1.sql

  python_bdd_imserso:
      container_name: python
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
        - postgres  
 
      
      
